name: Build Aimbot
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NDK
        uses: nvioletti/setup-ndk@v1
        with:
          ndk-version: r21e
      - name: Build with ndk-build (Fixed Path)
        run: |
          export PATH=$ANDROID_NDK_HOME:$PATH
          ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=jni/Android.mk NDK_APPLICATION_MK=jni/Application.mk
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libaimbot-arm32
          path: libs/armeabi-v7a/libriski_aimbot.so
